### ISSUE TITLE
Fix mainmenu

### ISSUE THREAD

**Issue by superhealing** [superhealing/kappar#12]
I think title is enough

**Comment by superhealing** [comment]
Should be enough.

**Comment by superhealing** [comment]
Mainmenu still an problem

**Comment by PurplikDev** [comment]
And will because Rongmario did something with FML

**Comment by superhealing** [comment]
> And will because Rongmario did something with FML

At start, which mods do that?

**Comment by PurplikDev** [comment]
That Loli thing

**Comment by superhealing** [comment]
> That Loli thing

https://www.curseforge.com/minecraft/mc-mods/sneedasm?
Try launching pack removing sneedasm

**Comment by PurplikDev** [comment]
Scale is still a bit weird but it fixed the text

**Comment by superhealing** [comment]
> Scale is still a bit weird but it fixed the text

Then scale must be something wrong with customainmenu config, looks like require some fixing, probably something we missed or you missed to pull request.

**Comment by PurplikDev** [comment]
Purplik literally edited the file as it was and refreshed and it was still broken, it's not the config

**Comment by superhealing** [comment]
*something* must be wrong here, i didn't add any other mods that might interfere with mainmenu

**Comment by PurplikDev** [comment]
Well, the something is not the script, Purplik checked with 2 clients. Same configs, same settings just one with only CMM and the other one is the pack so the something has to be one of the mods you added. 
In modding Everything is connected with everything.

**Comment by superhealing** [comment]
Issue found, is loliasm. looks like additional text on mainmenu caused this issue. I will keep this issue open until this issue is fixed.

**Comment by PurplikDev** [comment]
Well, it is fixed now

**Comment by superhealing** [comment]
I don't believe you, post screenshot.

**Comment by PurplikDev** [comment]
![2021-12-31_13 17 45](https://user-images.githubusercontent.com/60230933/147822944-48fac5ad-9b8b-4fd9-b6b4-485cc259f6e9.png)

**Comment by superhealing** [comment]
Fixed
