### ISSUE TITLE
Make new world default to OTG

### ISSUE THREAD

**Issue by superhealing** [superhealing/kappar#18]

**Comment by superhealing** [comment]
https://www.curseforge.com/minecraft/mc-mods/default-world-generator-port

**Comment by superhealing** [comment]
There is issue to make OTG as default especially that forcefully will crash the game.

**Comment by PurplikDev** [comment]
You can't make it "default" since it has a special button on the world creation screen. Also when you go though the vanilla Terrain gen options OTG is not an option
