### ISSUE TITLE
Additions to mods

### ISSUE THREAD

**Issue by superhealing** [superhealing/kappar#21]
https://www.curseforge.com/minecraft/mc-mods/gambling-style
https://www.curseforge.com/minecraft/mc-mods/village-names
https://www.curseforge.com/minecraft/mc-mods/smooth-scrolling-everywhere
https://www.curseforge.com/minecraft/mc-mods/thaumic-wonders ?

**Comment by PurplikDev** [comment]
1) Seems interesting
2) Useless
3) Eh, sire why not
4) **HECK NO, GET THIS CRAP OUT OF HERE**

**Comment by superhealing** [comment]
https://www.curseforge.com/minecraft/mc-mods/ender-io-endergy
https://www.curseforge.com/minecraft/mc-mods/ender-io-zoo
https://www.curseforge.com/minecraft/mc-mods/stellar-fluid-conduits
https://www.curseforge.com/minecraft/mc-mods/ender-io-forestry

**Comment by PurplikDev** [comment]
Let's stop adding mods ok? The mod list is stable and finished. These mods are not in because Queen did not want to add them
