### ISSUE TITLE
Remove Thaumic Speedup

### ISSUE THREAD

**Issue by PurplikDev** [superhealing/kappar#24]
Since it was added it broke my scripts for the recipes

**Comment by superhealing** [comment]
You don't need after removal of thaumic additions

**Comment by PurplikDev** [comment]
Since when is that removed

**Comment by superhealing** [comment]
https://github.com/superhealing/kappar/commit/0032df3e38eff6eb507f62225c1ab4f943a56cfb
#23

**Comment by PurplikDev** [comment]
Hmm, ok. Purplik won't complain even tho it was a joke

**Comment by superhealing** [comment]
Still, that might reduce heavy speed, which i didn't yet analyze, but i will in next second.

**Comment by superhealing** [comment]
I feel like thaumic additions adds too much i guess? If you want back pull request.
