### ISSUE TITLE
Disabling Techgun gadgets?

### ISSUE THREAD

**Issue by PurplikDev** [superhealing/kappar#27]
There are some Techgun items that make some stuff kinda pointless.

For example a Mask that gets rid of Wither potion effect

**Comment by superhealing** [comment]
I guess? but not other mods do that? example botania?

**Comment by superhealing** [comment]
Also if is way too easy to get, i might consider retweak at recipes or enabling hard mode on config perhaps if exist?

**Comment by PurplikDev** [comment]
Ring of Odin :/

**Comment by superhealing** [comment]
What about it? Since is default, i can't do mostly anything yet, if you do pull request to make harder both options feel free to do it.

**Comment by PurplikDev** [comment]
Ring of Odin is other item that gets rid of these effects if Purplik recalls correctly. It is a drop from the Gaia Guardian so we can't make it harder.

**Comment by PurplikDev** [comment]
Ok nvm, it isn't Odin

**Comment by superhealing** [comment]
After private discussion, we consider this issue resolved, and not push any changes.

**Comment by PurplikDev** [comment]
What discussion
