### ISSUE TITLE
Testing period

### ISSUE THREAD

**Issue by superhealing** [superhealing/kappar#34]
I did saw couple issues with loading time, however need tons of testing for that :

all tests need to do twice.
with each testing with respective name
files : debug.log, crafttweaker.log, latest.log
1) test without vanillafix, post here
2) test without speedasm + mixins (but keep vanillafix) 
3) both scenarios
4) test with current pack without anything, like keep vanillafix and speedasm

This is not the end, they may follow more testing, eg openj9 etc.

**Comment by PurplikDev** [comment]
Didn't we remove Speedasm before?

**Comment by superhealing** [comment]
> Didn't we remove Speedasm before?

No, stick with ontopic and further discussion do another place.

**Comment by HelpMySpacebarBroke** [comment]
Working on this

**Comment by HelpMySpacebarBroke** [comment]
All tests done with 8 out of 16 gb allocated, with only curseforge and github in background.

(4, nothing changed) 1. 

[crafttweaker.log](https://github.com/superhealing/kappar/files/8055935/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8055937/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8055944/latest.log)

(4, nothing changed) 2.

[crafttweaker.log](https://github.com/superhealing/kappar/files/8055957/crafttweaker.log)
[latest.log](https://github.com/superhealing/kappar/files/8055965/latest.log)
[debug.log](https://github.com/superhealing/kappar/files/8055970/debug.log)

**Comment by HelpMySpacebarBroke** [comment]
(1, removed Vanillafix) 1.

[crafttweaker.log](https://github.com/superhealing/kappar/files/8056000/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8056001/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8056002/latest.log)

(1, removed Vanillafix) 2.

[crafttweaker.log](https://github.com/superhealing/kappar/files/8056015/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8056016/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8056019/latest.log)

**Comment by HelpMySpacebarBroke** [comment]
(2, readded Vanillafix and removed loliasm and mixinbooter) 1.

[crafttweaker.log](https://github.com/superhealing/kappar/files/8056059/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8056063/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8056065/latest.log)

(2, readded Vanillafix and removed loliasm and mixinbooter) 2.

[crafttweaker.log](https://github.com/superhealing/kappar/files/8056085/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8056081/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8056089/latest.log)

**Comment by HelpMySpacebarBroke** [comment]
(3, removed vanillafix again) 1.

[crafttweaker.log](https://github.com/superhealing/kappar/files/8056129/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8056131/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8056133/latest.log)

(3, removed vanillafix again) 2. Crash? 
[crash-2022-02-13_18.02.24-client.txt](https://github.com/superhealing/kappar/files/8056146/crash-2022-02-13_18.02.24-client.txt)

(3, removed vanillafix again) 3.
[crafttweaker.log](https://github.com/superhealing/kappar/files/8056165/crafttweaker.log)
[debug.log](https://github.com/superhealing/kappar/files/8056166/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8056172/latest.log)

**Comment by HelpMySpacebarBroke** [comment]
Close issue?

**Comment by superhealing** [comment]
Ok analyze concluded that didn't do anything better since they do worse, the best result i did find is 370secs.

**Comment by HelpMySpacebarBroke** [comment]
[debug.log](https://github.com/superhealing/kappar/files/8104494/debug.log)
[latest.log](https://github.com/superhealing/kappar/files/8104528/latest.log)
[crafttweaker.log](https://github.com/superhealing/kappar/files/8104529/crafttweaker.log)
Regarding new update

**Comment by superhealing** [comment]
> [debug.log](https://github.com/superhealing/kappar/files/8104494/debug.log) [latest.log](https://github.com/superhealing/kappar/files/8104528/latest.log) [crafttweaker.log](https://github.com/superhealing/kappar/files/8104529/crafttweaker.log) Regarding new update

Not too bad, an increase around 30 seconds is okay.
