### ISSUE TITLE
Gameplay testing

### ISSUE THREAD

**Issue by superhealing** [superhealing/kappar#35]
There need be quite good things to verify.

1) Oregen
2) Mobs (other dims, etc hardness/ difficulty)
3) Recipes (too op or is gamebreaking, but need to be checked out)
4) Thaumcraft (especially looking at you without scream after 100 portals without that thing)
5) Galacticraft
6) Shaders or anything similar, morewever this is kinda optional.
And the last and least, stresstest the oregen, especially looking for loots.
Probably the last, find anything that may fit here?

**Comment by PurplikDev** [comment]
Elaborate point 4 please, I don't really understand

**Comment by sudo-CuriousLad** [comment]
What do we need to verify in Galacticraft? like if the dims don't crash or smth?

**Comment by PurplikDev** [comment]
If features that shouldn't ve there don't spawn there for example Tinkers' Islands or TG mobs

**Comment by sudo-CuriousLad** [comment]
I see. I'll check after classes, thanks. (btw I'm taking a one week break from discord so not available on there till the 18th)
