### ISSUE TITLE
Quark Caves Suggestion

### ISSUE THREAD

**Issue by PurplikDev** [superhealing/kappar#5]
Disabeling special Quark caves like the spider one or slime one and instead turning on an experimental version of giant caves that is fun to go though and explore.

**Comment by superhealing** [comment]
> Disabeling special Quark caves like the spider one or slime one and instead turning on an experimental version of giant caves that is fun to go though and explore.

Does "special" quark caves apply to diorite/slate biome?

**Comment by PurplikDev** [comment]
They aren't really a biome, it's a way they are distributed and imo it should be disabled too, it makes it spawn the vanilla way instead of the huge balls of the special stone underground.

**Comment by superhealing** [comment]
Done
